free(xbc[0]);
free(ybc[0]);
free(zbc[0]);
free(ubc[0]);
free(vbc[0]);
free(wbc[0]);

free(xlc[0]);
free(ylc[0]);
free(zlc[0]);
free(xrc[0]);
free(yrc[0]);
free(zrc[0]);

free(plc[0]);
free(prc[0]);

free(xp[0]);
free(zp[0]);
free(up[0]);
free(wp[0]);
free(box[0]);

free(xbc);
free(ybc);
free(zbc);
free(ubc);
free(vbc);
free(wbc);

free(xlc);
free(ylc);
free(zlc);
free(xrc);
free(yrc);
free(zrc);

free(plc);
free(prc);

free(xp);
free(zp);
free(up);
free(wp);
free(box);

delete [] ba;
delete [] fsi;
